### ISSUE TITLE
Build failing: Custom data types

### ISSUE THREAD

**Issue by elijahrockers** [VUIIS/dax#118]
I followed the instructions on the wiki for adding the freesurfer and proc modules, but I get a build error:

```
    [exec]     [javac] Compiling 1418 source files to /xnat/deployments/xnat/target/classes
    [exec] /xnat/deployments/xnat/target/src/org/nrg/xdat/om/base/BaseFsAparcregionanalysisRegion.java:18: cannot find symbol
    [exec] symbol: class AutoFsAparcregionanalysisRegion
    [exec] public abstract class BaseFsAparcregionanalysisRegion extends AutoFsAparcregionanalysisRegion {
    [exec]                                                               ^
    [exec] Note: Some input files use or override a deprecated API.
    [exec] Note: Recompile with -Xlint:deprecation for details.
    [exec] Note: Some input files use unchecked or unsafe operations.
    [exec] Note: Recompile with -Xlint:unchecked for details.
    [exec] 1 error
    [exec] 
    [exec] BUILD FAILED
    [exec] File...... /xnat/plugin-resources/cache/maven-java-plugin-1.5/plugin.jelly
    [exec] Element... ant:javac
    [exec] Line...... 63
    [exec] Column.... 48
    [exec] Compile failed; see the compiler error output for details.
    [exec] Total time: 8 seconds
    [exec] Finished at: Thu Sep 22 10:03:21 CDT 2016
    [exec] 
    [exec] [ERROR] Result: 70
BUILD SUCCESSFUL
Total time: 45 seconds
Finished at: Thu Sep 22 10:03:21 CDT 2016

```

I tried a similar install on my VM and it worked, so something on the production XNAT is different, but unfortunately the guy who configured it is gone. I would appreciate any advice on how to proceed from here... I backed up the SQL database manually before the attempt, and the images themselves are backed up nightly.

**Comment by elijahrockers** [comment]
Found this up closer to the top of the builder output:

```

    [java] org.nrg.xft.exception.FieldNotFoundException: Field not found: 'fs:aparcRegionAnalysis/NumVert'
    [java] 	at org.nrg.xft.schema.Wrappers.GenericWrapper.GenericWrapperElement.TranslateXMLPathToTables(GenericWrapperElement.java:2646)
    [java] 	at org.nrg.xft.search.QueryOrganizer.buildJoin(QueryOrganizer.java:243)
    [java] 	at org.nrg.xdat.search.QueryOrganizer.buildJoin(QueryOrganizer.java:440)
    [java] 	at org.nrg.xdat.search.QueryOrganizer.buildQuery(QueryOrganizer.java:1162)
    [java] 	at org.nrg.xdat.search.QueryOrganizer.buildQuery(QueryOrganizer.java:1128)
    [java] 	at org.nrg.xdat.search.DisplaySearch.getSQLQuery(DisplaySearch.java:512)
    [java] 	at org.nrg.xdat.display.DisplayManager.GetCreateViewsSQL(DisplayManager.java:632)
    [java] 	at org.nrg.xdat.XDAT.GenerateUpdateSQL(XDAT.java:295)
    [java] 	at GenerateAllUpdateFiles.process(GenerateAllUpdateFiles.java:127)
    [java] 	at org.nrg.xft.commandPrompt.CommandPromptTool._process(CommandPromptTool.java:205)
    [java] 	at org.nrg.xft.commandPrompt.CommandPromptTool.run(CommandPromptTool.java:163)
    [java] 	at org.nrg.xft.commandPrompt.CommandPromptTool.<init>(CommandPromptTool.java:77)
    [java] 	at GenerateAllUpdateFiles.<init>(GenerateAllUpdateFiles.java:27)
    [java] 	at GenerateAllUpdateFiles.main(GenerateAllUpdateFiles.java:31)
    [copy] Copying 1 file to /xnat/deployments/xnat/sql
```

**Comment by elijahrockers** [comment]
According to the discussion group, this is very likely a problem with the version. (1.6.3)
