### ISSUE TITLE
Dax Test appears to be broken

### ISSUE THREAD

**Issue by atbenmurray** [VUIIS/dax#190]
Just as it says: running dax test on a project results in the following exception:

Traceback (most recent call last):
  File "/home/ben/git/freshdax/bin/dax_tools/dax", line 201, in <module>
    args.do_not_remove, args.nb_sess)
  File "/home/ben/git/freshdax/dax/dax_tools_utils.py", line 584, in testing
    tests.run_test(project, sessions, nb_sess)
  File "/home/ben/git/freshdax/dax/dax_tools_utils.py", line 1594, in run_test
    self.run_test_settings(project, sessions)
  File "/home/ben/git/freshdax/dax/dax_tools_utils.py", line 2049, in run_test_settings
    self.display_settings()
  File "/home/ben/git/freshdax/dax/dax_tools_utils.py", line 2112, in display_settings
    print_processor(processor)
  File "/home/ben/git/freshdax/dax/dax_tools_utils.py", line 2169, in print_processor
    if proc_obj.type == 'scan':
AttributeError: 'AutoProcessor' object has no attribute 'type'

**Comment by baxpr** [comment]
No updates in a long time - I'm expiring this ticket, but please bring it back if it's still an issue
