### ISSUE TITLE
Exception running dax build

### ISSUE THREAD

**Issue by davecash75** [VUIIS/dax#210]
I am getting an exception running dax build for my yaml process with the following trackback.
I'm suspecting that this is part due to a legacy project that does not yet use the diskq feature (as this code occurs in the else block of the if statement ` if self.launcher_type in ['diskq-xnat', 'diskq-combined']:` ) trying to call the function get_scan_task in processors.py and trying to pass the xnat interface to it but no longer needs to. While the version installed is slightly older (0.9.rc1), it appears that the same call is still happening in the master.
AS this appears to be more of a legacy issue, is the quickest fit to change the settings on our dax setup so that it uses diskq instead?
Many thans,
David Cash
`
2019-07-19 23:30:25,629 - CRITICAL - launcher - Exception class <type 'exceptions.TypeError'> caught with message get_task() takes exactly 3 arguments (4 given)
2019-07-19 23:30:25,652 - CRITICAL - launcher - Traceback (most recent call last):
  File "/share/apps/cmic/anaconda/anaconda2/envs/proc_dax_2019_01_10/lib/python2.7/site-packages/dax/launcher.py", line 603, in build_project
    exp_mods, scan_mods)
  File "/share/apps/cmic/anaconda/anaconda2/envs/proc_dax_2019_01_10/lib/python2.7/site-packages/dax/launcher.py", line 683, in build_session
    self.build_scan_processors(intf, cscan, scan_proc_list)
  File "/share/apps/cmic/anaconda/anaconda2/envs/proc_dax_2019_01_10/lib/python2.7/site-packages/dax/launcher.py", line 843, in build_scan_processors
    scan_task = scan_proc.get_task(xnat, cscan, res_dir)
TypeError: get_task() takes exactly 3 arguments (4 given)
`

**Comment by atbenmurray** [comment]
I'm taking a look at it now

**Comment by atbenmurray** [comment]
Ok, I've made a pull request on the fix for this issue. Hopefully it should be merged very soon, but in the meanwhile, you can check it out using the following link. https://github.com/VUIIS/dax/tree/210_exception_running_dax_build

**Comment by bud42** [comment]
merged
