### ISSUE TITLE
readline requirement?

### ISSUE THREAD

**Issue by baxpr** [VUIIS/dax#268]
Running in a venv on the cluster, we get this error if lmod is not used to load Python/3.6.3:

```
Traceback (most recent call last):
  File "/gpfs52/data/mcr/centos7/venv/dax/bin/dax", line 13, in <module>
    import dax
  File "/gpfs52/data/mcr/centos7/venv/dax/lib/python3.6/site-packages/dax/__init__.py", line 7, in <module>
    from . import dax_tools_utils
  File "/gpfs52/data/mcr/centos7/venv/dax/lib/python3.6/site-packages/dax/dax_tools_utils.py", line 21, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
```

Is this something about the cluster, or should readline be included as a dependency of dax?

**Comment by bud42** [comment]
It looks like readline is only used by dax setup for tab completion of file paths. Anyone opposed to removing this functionality so we can remove the readline dependency?

**Comment by bud42** [comment]
Let's go ahead and remove it since we are moving paths to the redcap instance settings database.
