### ISSUE TITLE
Bug in emailer

### ISSUE THREAD

**Issue by baxpr** [VUIIS/dax#281]
Looks like dax can't properly handle whatever it's getting from the settings file?

```
XNAT timeout, emailing admin
```

<details>
  <summary>Preceding errors I don't think are relevant</summary>

```
XNAT timeout, emailing admin
Traceback (most recent call last):
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/dax/XnatUtils.py", line 218, in _exec
    result = super()._exec(
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/pyxnat/core/interfaces.py", line 337, in _exec
    response = request(method, uri, headers, body, kwargs)
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/pyxnat/core/interfaces.py", line 327, in request
    response = self._http.delete(uri, headers=headers, data=body,
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/requests/sessions.py", line 612, in delete
    return self.request('DELETE', url, **kwargs)
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

</details>

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rogersbp/miniconda3/envs/dax/bin/Xnatinfo", line 348, in <module>
    utils.run_tool(__exe__, __description__, add_to_parser, __purpose__,
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/dax/xnat_tools_utils.py", line 182, in run_tool
    run_tool_fct(args)
  File "/Users/rogersbp/miniconda3/envs/dax/bin/Xnatinfo", line 315, in run_xnat_info
    report_project(xnat, args.project, args.ignore_scans,
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/dax/XnatUtils.py", line 182, in __exit__
    self.disconnect()
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/dax/XnatUtils.py", line 191, in disconnect
    super(InterfaceTemp, self).disconnect()
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/pyxnat/core/interfaces.py", line 498, in disconnect
    self._exec('/data/JSESSION', method='DELETE')
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/dax/XnatUtils.py", line 232, in _exec
    _to = DAX_SETTINGS.get_admin_email().split(',')
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by baxpr** [comment]
Just realized this was with 1.3.0. Can't replicate the issue in 1.4.1, so closing
