### ISSUE TITLE
Logic issue in XnatUtils.has_resource

### ISSUE THREAD

**Issue by baxpr** [VUIIS/dax#291]
https://github.com/VUIIS/dax/blob/88fa3e5f93a503ca767279ed0aecbbf46ab2121c/dax/XnatUtils.py#L2758

If the resource doesn't exist, this throws the error below instead of politely returning 'false' like it's supposed to. Looks like it needs to check for 'None' somewhere maybe:

```
2020-09-02 15:40:31,415 - CRITICAL - launcher - Caught exception building sessions 603854632982
2020-09-02 15:40:31,415 - CRITICAL - launcher - Exception class <class 'ValueError'> caught with message invalid literal for int() with base 10: ''
2020-09-02 15:40:31,423 - CRITICAL - launcher - Traceback (most recent call last):
  File "/gpfs52/data/mcr/centos7/venv/dax/lib/python3.6/site-packages/dax/launcher.py", line 556, in build_project
    sessions=cached_sessions)
  File "/gpfs52/data/mcr/centos7/venv/dax/lib/python3.6/site-packages/dax/launcher.py", line 618, in build_session
    self.build_scan_modules(intf, cscan, scan_mod_list)
  File "/gpfs52/data/mcr/centos7/venv/dax/lib/python3.6/site-packages/dax/launcher.py", line 686, in build_scan_modules
    if scan_mod.needs_run(cscan, xnat):
  File "/data/mcr/centos7/dax_modules/Module_dcm2niix.py", line 66, in needs_run
    if not XnatUtils.has_resource(cscan, 'DICOM'):
  File "/gpfs52/data/mcr/centos7/venv/dax/lib/python3.6/site-packages/dax/XnatUtils.py", line 2767, in has_resource
    return (len(res_list) > 0) and (int(res_list[0]['file_count']) > 0)
ValueError: invalid literal for int() with base 10: ''
```

**Comment by bud42** [comment]
fixed in dax v2.0.0
