### ISSUE TITLE
dax setup on Windows

### ISSUE THREAD

**Issue by rvangala936** [VUIIS/dax#298]
Hello,
 I installed the dax per https://dax.readthedocs.io/en/latest/ and ran the dax setup on Windows Git bash an d got the following error. Can you please let me know how to fix this issue?

Warning: No settings.ini file found.Warning: No settings.ini file found.Warning: C:\Users\<USER_NAME>\.dax_settings.ini No header cluster found in config file C:\Users\<USER_NAME>\.dax_settings.ini
########## DAX_SETUP ##########
Script to setup the ~/.dax_settings.ini files for your dax installation.

Traceback (most recent call last):
  File "C:/Python38/Scripts/dax", line 246, in <module>
    dax_tools.setup_dax_package()
  File "C:\python38\lib\site-packages\dax\dax_tools_utils.py", line 566, in setup_dax_package
    set_xnat_netrc()
  File "C:\python38\lib\site-packages\dax\dax_tools_utils.py", line 2419, in set_xnat_netrc
    netrc_obj = DAX_Netrc()
  File "C:\python38\lib\site-packages\dax\dax_settings.py", line 62, in __init__
    self.is_secured()
  File "C:\python38\lib\site-packages\dax\dax_settings.py", line 73, in is_secured
    raise DaxNetrcError(msg % self.netrc_file)
dax.errors.DaxNetrcError: Wrong permission on C:\Users\<USER_NAME>\.netrc file. Only you should have read and write access. (None, line None)

Thanks
Ravi

**Comment by KarthikMasi** [comment]
Hi Ravi,

I recommend using "Windows Subsystem for Linux(WSL https://docs.microsoft.com/en-us/windows/wsl/install-win10)" for installing DAX on Windows. DAX is not supported on Windows and Git bash does not provide "enough Linux" to get a work around. 

Thanks
Karthik

**Comment by rvangala936** [comment]
Wsl2 worked! thank you.
