### ISSUE TITLE
fdest: error when not provided

### ISSUE THREAD

**Issue by baxpr** [VUIIS/dax#313]
The below error when fdest is not specified for a file input resource in the processor yaml. Yaml was this but without the fdest in the scan_fmri resource:
https://github.com/VUIIS/yaml_processors/blob/baxpr-edat/gf-edat-Oddball_v2.1.0.yaml

```
2021-03-04 17:11:31,347 - DEBUG - processor_parser - checking status of each artefact
2021-03-04 17:11:31,347 - DEBUG - processor_parser - checking status:scan_fmri
2021-03-04 17:11:31,347 - DEBUG - processor_parser - mapping params to artefact resources
2021-03-04 17:11:31,347 - DEBUG - processor_parser - mapping:eprime_txt
2021-03-04 17:11:31,350 - DEBUG - XnatUtils - _exec:GET:/data/projects/GenFac_HWZ/subjects/141660/experiments/141660/scans/1001/resources/EPRIME_TXT/files?format=csv&columns=path,xsiType
2021-03-04 17:11:32,248 - CRITICAL - launcher - Caught exception building sessions 141660
2021-03-04 17:11:32,249 - CRITICAL - launcher - Exception class <class 'KeyError'> caught with message 'fdest'
2021-03-04 17:11:32,251 - CRITICAL - launcher - Traceback (most recent call last):
  File "/home/duettwe/miniconda3/envs/dax2/lib/python3.8/site-packages/dax/launcher.py", line 571, in build_project
    self.build_session(
  File "/home/duettwe/miniconda3/envs/dax2/lib/python3.8/site-packages/dax/launcher.py", line 646, in build_session
    self.build_auto_processors(csess, auto_proc_list, sessions)
  File "/home/duettwe/miniconda3/envs/dax2/lib/python3.8/site-packages/dax/launcher.py", line 766, in build_auto_processors
    (proc_status, qc_status) = xtask.build_task(
  File "/home/duettwe/miniconda3/envs/dax2/lib/python3.8/site-packages/dax/task.py", line 1554, in build_task
    cmds = self.build_commands(assr, sessions, jobdir, resdir)
  File "/home/duettwe/miniconda3/envs/dax2/lib/python3.8/site-packages/dax/task.py", line 1597, in build_commands
    return self.processor.build_cmds(
  File "/home/duettwe/miniconda3/envs/dax2/lib/python3.8/site-packages/dax/processors.py", line 695, in build_cmds
    var2val, input_list = self.parser.find_inputs(
  File "/home/duettwe/miniconda3/envs/dax2/lib/python3.8/site-packages/dax/processor_parser.py", line 315, in find_inputs
    fdest = cur_res['fdest']
KeyError: 'fdest'
2021-03-04 17:11:32,251 - DEBUG - XnatUtils - _exec:DELETE:/data/JSESSION
2021-03-04 17:11:32,261 - INFO - bin - finished build, End Time: 2021-03-04 17:11:32.261349
```

**Comment by baxpr** [comment]
@bud42 I think this is fixed by https://github.com/VUIIS/dax/pull/341 yeah?

**Comment by baxpr** [comment]
Yeah.
