### ISSUE TITLE
Bug in XnatUtils.py get_scan_resources

### ISSUE THREAD

**Issue by baxpr** [VUIIS/dax#315]
```
xnat = dax.XnatUtils.get_interface()
rsrcs = xnat.get_scan_resources(project,subject,session,scan)
```

```
Traceback (most recent call last):
  File "./delete_eprime_txt_resource.py", line 18, in <module>
    rsrcs = xnat.get_scan_resources(fscan['project_id'],fscan['subject_label'],fscan['session_label'],fscan['scan_id'])
  File "/Users/rogersbp/miniconda3/envs/dax/lib/python3.8/site-packages/dax/XnatUtils.py", line 906, in get_scan_resources
    resource_list = intf._get_json(post_uri)
NameError: name 'intf' is not defined
```

**Comment by baxpr** [comment]
Just need `self.` instead of `intf.` maybe?

**Comment by baxpr** [comment]
I have a workaround by the way, so no urgency on this from me
