### ISSUE TITLE
self._getjson bug in XnatUtils.py

### ISSUE THREAD

**Issue by baxpr** [VUIIS/dax#325]
With dax==2.1.0

```
from dax import XnatUtils
with XnatUtils.get_interface() as xnat:
    projects = xnat.get_projects()
```

```
Traceback (most recent call last):
  File "./xnat_counts.py", line 5, in <module>
    projects = xnat.get_projects()
  File "/Users/rogersbp/miniconda3/envs/dax-2.1/lib/python3.6/site-packages/dax/XnatUtils.py", line 397, in get_projects
    return self._getjson(PROJECTS_URI)
AttributeError: 'InterfaceTemp' object has no attribute '_getjson'
```

**Comment by baxpr** [comment]
Some other functions are using `self._get_json`, so is this maybe a typo or historical artifact?
