### ISSUE TITLE
Error building when no scans in session

### ISSUE THREAD

**Issue by baxpr** [VUIIS/dax#378]
dax should probably notice this, log that there are no scans, and move on rather than causing an exception

```
2022-06-04 21:32:02,940 - INFO - launcher - + Session 209372: building...
2022-06-04 21:32:02,941 - DEBUG - launcher - == Build modules (count:0) ==
2022-06-04 21:32:02,941 - DEBUG - XnatUtils - _exec:GET:/data/projects/ASDREST/subjects/209372/experiments?format=csv&columns=ID,xsiType,label
2022-06-04 21:32:03,084 - DEBUG - XnatUtils - _exec:GET:/data/projects/ASDREST/subjects/209372/experiments?columns=ID,xnat:mrSessionData/meta/last_modified&format=csv
2022-06-04 21:32:05,765 - DEBUG - XnatUtils - _exec:GET:/data/projects/ASDREST/subjects/209372/experiments?format=csv&columns=ID,label
2022-06-04 21:32:05,916 - DEBUG - launcher - == Build auto processors ==
2022-06-04 21:32:05,916 - DEBUG - processor_parser - session is first, including pets
2022-06-04 21:32:05,916 - DEBUG - processors_v3 - session is first, including pets
2022-06-04 21:32:05,916 - CRITICAL - launcher - Caught exception building sessions 209372
2022-06-04 21:32:05,916 - CRITICAL - launcher - Exception class <class 'IndexError'> caught with message list index out of range
2022-06-04 21:32:05,932 - CRITICAL - launcher - Traceback (most recent call last):
  File "/gpfs52/data/mcr/centos7/venv/dax/lib/python3.8/site-packages/dax/launcher.py", line 598, in build_project
    self.build_session(
  File "/gpfs52/data/mcr/centos7/venv/dax/lib/python3.8/site-packages/dax/launcher.py", line 808, in build_session
    self.build_auto_processors(csess, auto_proc_list, sessions)
  File "/gpfs52/data/mcr/centos7/venv/dax/lib/python3.8/site-packages/dax/launcher.py", line 904, in build_auto_processors
    mapping = auto_proc.parse_session(csess, mrs, pets)
  File "/gpfs52/data/mcr/centos7/venv/dax/lib/python3.8/site-packages/dax/processors_v3.py", line 708, in parse_session
    artefacts_by_input = self._map_artefacts_to_inputs(csess, pets)
  File "/gpfs52/data/mcr/centos7/venv/dax/lib/python3.8/site-packages/dax/processors_v3.py", line 1144, in _map_artefacts_to_inputs
    artefacts_by_input[i] = [sorted_info[idx_multi-1][0]]
IndexError: list index out of range
```

**Comment by baxpr** [comment]
duplicate of #376
