### ISSUE TITLE
Xnatdownload bugs

### ISSUE THREAD

**Issue by baxpr** [VUIIS/dax#413]
1. `-c` option does not work - why? And, it's requiring the quality field which does not make sense here. Error: http://xnatbug.vandyxnat.org/bugzilla/attachment.cgi?id=384

2. The resume download feature does not work either:
```
Traceback (most recent call last):
  File "/Users/rogersbp/miniconda3/envs/dax/bin/Xnatdownload", line 1378, in <module>
    get_xnat_information()
  File "/Users/rogersbp/miniconda3/envs/dax/bin/Xnatdownload", line 489, in get_xnat_information
    scans_list, asses_list, last_dl_date, old_rows = extract_information()
  File "/Users/rogersbp/miniconda3/envs/dax/bin/Xnatdownload", line 281, in extract_information
    scans_dl_dict, asses_dl_dict, last_dl_date, old_rows = read_report()
  File "/Users/rogersbp/miniconda3/envs/dax/bin/Xnatdownload", line 226, in read_report
    csvreader.__next__()[0].split('=')[1]
IndexError: list index out of range
```

And since this has come up, there's a more general question which is, fix a couple of little bugs, or just refactor the CSV read/write entirely using pandas so that the CSV read/write part of the code is more versatile and less hassle to use and maintain?

**Comment by baxpr** [comment]
Download resume was thought fixed last fall - not sure why broken again? This is in dax 2.9.7
